### PR TITLE
Fix sysid-projects not using newest allwpilib dev builds

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Comment by calcmogul** [comment]
It was only pulling 2022.1.1-beta-3 when it should have pulled the commits to main since then as well.

**Review by sciencewhiz — COMMENTED** [review]
This will work on CI, but will still pull in the latest release installed locally unless you also add `wpi.maven.useLocal = false`

**Comment by calcmogul** [comment]
Do we want it to see local publishes too? idk

**Comment by sciencewhiz** [comment]
That's also needed for local publishes. https://github.com/wpilibsuite/GradleRIO/issues/528#issuecomment-941947942

**Review by prateekma — APPROVED** [review]

**Pull request merged**
