### PR TITLE
Remove median filter

### PR DESCRIPTION
**Pull request by Oblarg**
Removes the median filter, as it no longer appreciably improves the quality of the fit on actual robot data (and in scenarios where it does, the sensor noise should probably be fixed anyway...)

### CODE REVIEW

**Review by calcmogul — CHANGES_REQUESTED** [review]
You forgot to remove the MedianFilter.h include from FilteringUtils.cpp.

**Comment by calcmogul** [comment]
The fit on the following data is much worse without the median filter.
[sysid_data20220119-150715.json.txt](https://github.com/wpilibsuite/sysid/files/7943784/sysid_data20220119-150715.json.txt)

With median filter:
median-filter

Without median filter:
no-median-filter

If our stance is to fix the measurement noise, how would one do that? This data was generated by sysid.

**Comment by Oblarg** [comment]
ooof, I had never seen data quite that bad.  Any idea what the setup is that's generating that?

**Comment by calcmogul** [comment]
Unfortunately, I don't know what the hardware setup was. I didn't ask for their generation JSON.

**Comment by Oblarg** [comment]
Okay, noted; I'll change the PR to simply defaulting the filter to off (i.e. window size 1), since it does dilute the acceleration gain if the noise is acceptable.

**Comment by calcmogul** [comment]
Sounds good.

**Pull request closed without merging**
