### PR TITLE
Separate forward/backward plots

### PR DESCRIPTION
**Pull request by Oblarg**
Also fixes a minor crash bug involving attempting to refresh the plots when no data are available.

### CODE REVIEW

**Comment by Oblarg** [comment]
image

**Comment by calcmogul** [comment]
If I load a JSON, then click the analysis reset button, then try to choose "backward" in the direction combo box, it crashes. m_hasData isn't being set back to false when it should.

**Review by calcmogul — CHANGES_REQUESTED** [review]
If I load a JSON, then click the analysis reset button, then try to choose "backward" in the direction combo box, it crashes. m_hasData isn't being set back to false when it should.

**Comment by calcmogul** [comment]
We should look into refactoring the error handling at some point. We're approximating a state machine of some kind, but it's not formally defined, and we may not be catching all error conditions.

**Review by calcmogul — APPROVED** [review]

**Review by Piphi5 — APPROVED** [review]

**Pull request merged**
