### PR TITLE
Fix Doxygen HTML being empty

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Comment by calcmogul** [comment]
It still doesn't warn on undocumented free functions, and I can't figure out why.

**Comment by Piphi5** [comment]
This catches undocumented member variables and classes but not methods: 
My working theory right now is that a lot of the default values have been switched for some reason.
```
  case_sense_names false
  extension_mapping 'inc=C++', 'no_extension=C++'
  extract_all false
  extract_anon_nspaces true
  extract_static true
  file_patterns '*'
  full_path_names true
  generate_html true
  generate_latex false
  generate_treeview true
  hide_undoc_members false
  hide_undoc_classes false
  hide_undoc_relations false
  html_extra_stylesheet 'theme.css'
  html_timestamp true
  outputDir 'build/docs/'
  project_name 'SysId'
  project_logo 'sysid-application/src/main/native/resources/sysid-128.png'
  project_number wpilibVersioning.version.get()
  source 'sysid-application/src/integrationtest-utils', 'sysid-application/src/main/native/cpp', 'sysid-application/src/main/native/include', 'sysid-library/src', 'sysid-projects/src'
  quiet false
  recursive true
  strip_code_comments false
  use_mathjax true
  warn_as_error 'FAIL_ON_WARNINGS'
  warn_if_doc_error true
  warn_if_undocumented true
  warn_no_paramdoc true
  warnings true
  ```

**Comment by Piphi5** [comment]
Did the latest changes fix the issue?

**Comment by calcmogul** [comment]
I just rebased. I didn't change anything other than fixing a few new Doxygen errors.

**Comment by Piphi5** [comment]
> I just rebased. I didn't change anything other than fixing a few new Doxygen errors. We may have to admit defeat and accept that some docs is better than no docs.

Is this the path we ended up taking?

**Comment by calcmogul** [comment]
Yea. If we end up fixing the inclusion of free function docs, we can close the related issue.

**Pull request merged**
