### PR TITLE
Display time domain plots above voltage domain plots

### LINKED ISSUE #257: Put time domain plots before voltage domain plots
The time domain plots are more useful for determining goodness of fit in real scenarios than the voltage domain plots.

### PR DESCRIPTION
**Pull request by Piphi5**
Fixes #257

### CODE REVIEW

**Comment by Piphi5** [comment]
Currently, time steps vs time comes before voltage domain. Is this okay or should that be moved after the voltage domain fit?
image

**Comment by calcmogul** [comment]
I think that's fine.

**Review by calcmogul — APPROVED** [review]

**Review by calcmogul — CHANGES_REQUESTED** [review]
The combined diagnostics dialog layout got broken.

**Comment by calcmogul** [comment]
Screenshot_20211224_154806

**Comment by calcmogul** [comment]
I think the chart title order is hardcoded and relied on in a bunch of places in AnalyzerPlot.cpp.

**Comment by Piphi5** [comment]
Ah that makes sense

**Comment by Piphi5** [comment]
What if we didn't mess with the order for the combined diagnostics?

**Comment by calcmogul** [comment]
That's not an option without refactoring. We call the same plotting functions for both the normal view and the combined view.

**Comment by Piphi5** [comment]
Well I did also update the order for the combined diagnostics graph, here's what it looks like if I just revert that change:
image

**Comment by calcmogul** [comment]
I guess that's the easiest stop-gap solution. We should refactor that display code at some point though.

**Comment by Piphi5** [comment]
Yeah I'll make a new issue since the refactor is out of the scope of this issue/pr

**Review by calcmogul — APPROVED** [review]

**Pull request merged**
