### PR TITLE
Refactor dt filtering and tighten integration test tolerances

### PR DESCRIPTION
**Pull request by calcmogul**
Time deltas in the range 0ms to 500ms are used to compute the mean time
delta. Then, data points are only considered that are within 1ms of that
mean.

### CODE REVIEW

**Comment by Piphi5** [comment]
Wouldn't it be good (for development purposes at least) to be able to know/plot the values of all of the dt's? Just not sure how we would integrate the two types of dt's (maybe different colors for the ones removed) unless we want to just have the full data available for analysis through #100.

**Comment by calcmogul** [comment]
If we plotted both raw and filtered dts, the main difference is values within 1ms of the mean would be a different color.

**Review by prateekma — APPROVED** [review]

**Comment by Piphi5** [comment]
> Are the dts outside the 0ms to 500ms range what you had in mind?
Yeah, just so we know they exist.

**Review by prateekma — COMMENTED** [review]
I wonder if using the median would be better here? Since the dts usually tend to have pretty high outliers, I'm worried that we might get a mean with no dts in a 1 ms neighborhood of the mean.

**Comment by calcmogul** [comment]
The problem with that is the quality of the data rapidly deteriorates as dt deviates from the mean. There's a lot of outliers, but the mean is generally spot-on because there's a clump of datapoints close to the mean.

**Comment by prateekma** [comment]
Ok, I agree that if it works in CI, it will probably work in all other situations. I am still thinking of a better error reporting pipeline (also useful for #74) so we can work that in later.

**Comment by Piphi5** [comment]
Also, could we run the Integration Test CI multiple times to make sure that it really works?

**Comment by prateekma** [comment]
I reran it three times and it passed always.

**Comment by Piphi5** [comment]
So are all the dt's graphed or are negative ones excluded?

**Comment by calcmogul** [comment]
Negative is excluded because their nonsensical.

**Review by Piphi5 — APPROVED** [review]

**Pull request merged**
