### PR TITLE
Read voltage measurements from motor controllers

### LINKED ISSUE #370: Voltage should be measured from the motor controller when possible
see discussion here: https://www.chiefdelphi.com/t/sysid-tool/398381/51?u=oblarg

### PR DESCRIPTION
**Pull request by Piphi5**
Fixes #370

### CODE REVIEW

**Comment by Oblarg** [comment]
This should leverage the Rev/CTRE APIs where possible, as well.

**Comment by Piphi5** [comment]
I can use GetBusVoltage right?

**Comment by Oblarg** [comment]
I think?

**Comment by Piphi5** [comment]
My only issue with the current version of this is that we don't have any good way of unit testing the if/else statements for each vendor motor. If we were to change the name of the motor controllers that could be a major bug that would go unnoticed.

I think the most ideal way of solving this is to use the hardware types class that the sysid application uses to avoid getting mixed up. However, I don't know enough gradle to get that to work.

**Comment by Piphi5** [comment]
It would also be nice to have some sort of vendor verification that the methods here are the ones needed to get the proper voltage to motor reading.

**Comment by Piphi5** [comment]
@CodingWithFusion can you verify if [this code](https://github.com/Piphi5/sysid/blob/fix-voltage-measurement/sysid-library/src/main/cpp/logging/SysIdLogger.cpp#L62) is correct for getting the voltage applied to the motor for the venom?

**Review by calcmogul — APPROVED** [review]

**Pull request merged**
