### PR TITLE
Use higher order central finite difference for acceleration calc

### PR DESCRIPTION
**Pull request by calcmogul**
This gives much less noisy acceleration estimates.

### CODE REVIEW

**Comment by calcmogul** [comment]
Before:
before-central-finite-diff
After:
after-central-finite-diff

[arm-ci-failure.json.txt](https://github.com/wpilibsuite/sysid/files/6410278/arm-ci-failure.json.txt)

**Comment by Piphi5** [comment]
Would it be worth it to add tests?

**Comment by calcmogul** [comment]
Yea.

**Comment by calcmogul** [comment]
Unit tests for central finite difference have been added.

**Comment by calcmogul** [comment]
Removing the dt filtering improved the fit for the failed data I downloaded from previous CI runs for this PR.

**Comment by Piphi5** [comment]
Wasn't the removal of those dts necessary for some data recorded from frc-char?

**Comment by calcmogul** [comment]
It worked fine on the data I have locally, except for the following two. Their dts are also pretty good, so dt removal wouldn't have helped.

[top-characterization-data-20210317-1525_new.json.txt](https://github.com/wpilibsuite/sysid/files/6412083/top-characterization-data-20210317-1525_new.json.txt)
[bottom-characterization-data20210319-1504_new.json.txt](https://github.com/wpilibsuite/sysid/files/6412084/bottom-characterization-data20210319-1504_new.json.txt)

**Comment by Piphi5** [comment]
What was #113  referring to then?

**Comment by calcmogul** [comment]
The instability that PR fixed was probably caused by the poor acceleration calculation.

**Comment by Piphi5** [comment]
But doesn't flywheel data use new ols that isn't dependent on accel?

**Comment by calcmogul** [comment]
The acceleration affects the data trimming. I just tried running main without the dt removal, and it's still stable. I'm not sure why. The fact remains though that the CI was failing more often until I just removed it.

**Comment by Piphi5** [comment]
Alright that makes sense

**Review by prateekma — APPROVED** [review]

**Pull request merged**
